/**
 * Canonical error codes for the Get Gains API.
 *
 * Convention: SCREAMING_SNAKE_CASE, prefixed by domain.
 * Once shipped, codes are public API — add, never rename.
 */
export const ERROR_CODES = {
  // ── Cross-cutting ────────────────────────────────────────────────
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  UNEXPECTED_EXCEPTION: 'UNEXPECTED_EXCEPTION',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  // ── Upload ───────────────────────────────────────────────────────
  UPLOAD_FILE_TOO_LARGE: 'UPLOAD_FILE_TOO_LARGE',
  UPLOAD_INVALID_FILE_TYPE: 'UPLOAD_INVALID_FILE_TYPE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  UPLOAD_MISSING_FILE: 'UPLOAD_MISSING_FILE',
  UPLOAD_INVALID_PREFIX: 'UPLOAD_INVALID_PREFIX',
  UPLOAD_PRESIGN_FAILED: 'UPLOAD_PRESIGN_FAILED',

  // ── Auth ─────────────────────────────────────────────────────────
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_APP_USER_NOT_FOUND: 'AUTH_APP_USER_NOT_FOUND',
  AUTH_COACH_REQUIRED: 'AUTH_COACH_REQUIRED',
  AUTH_ADMIN_REQUIRED: 'AUTH_ADMIN_REQUIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_USER_BANNED: 'AUTH_USER_BANNED',
  AUTH_SIGNUP_DISABLED: 'AUTH_SIGNUP_DISABLED',
  AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  AUTH_SAME_PASSWORD: 'AUTH_SAME_PASSWORD',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_BAD_JWT: 'AUTH_BAD_JWT',
  AUTH_OAUTH_FAILED: 'AUTH_OAUTH_FAILED',
  AUTH_PROVIDER_ERROR: 'AUTH_PROVIDER_ERROR',
  AUTH_REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
  AUTH_CODE_EXCHANGE_FAILED: 'AUTH_CODE_EXCHANGE_FAILED',
  AUTH_TOKEN_GENERATION_FAILED: 'AUTH_TOKEN_GENERATION_FAILED',
  AUTH_ID_TOKEN_REQUIRED: 'AUTH_ID_TOKEN_REQUIRED',
  AUTH_ID_TOKEN_INVALID: 'AUTH_ID_TOKEN_INVALID',
  AUTH_OTP_COOLDOWN: 'AUTH_OTP_COOLDOWN',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_OTP_RATE_LIMITED: 'AUTH_OTP_RATE_LIMITED',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',

  // ── Subscription ─────────────────────────────────────────────────
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  SUBSCRIPTION_TIER_INSUFFICIENT: 'SUBSCRIPTION_TIER_INSUFFICIENT',
  SUBSCRIPTION_INVALID_SESSION: 'SUBSCRIPTION_INVALID_SESSION',

  // ── User ─────────────────────────────────────────────────────────
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_USERNAME_TAKEN: 'USER_USERNAME_TAKEN',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_COACH_NOT_FOUND: 'USER_COACH_NOT_FOUND',
  USER_COACH_ALREADY_SUBSCRIBED: 'USER_COACH_ALREADY_SUBSCRIBED',
  USER_COACH_NOT_ACCEPTING: 'USER_COACH_NOT_ACCEPTING',
  USER_COACH_AT_CAPACITY: 'USER_COACH_AT_CAPACITY',
  USER_COACH_NOT_SUBSCRIBED: 'USER_COACH_NOT_SUBSCRIBED',
  USER_COACH_ALREADY_UNSUBSCRIBED: 'USER_COACH_ALREADY_UNSUBSCRIBED',

  // ── Profile ──────────────────────────────────────────────────────
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_CREATE_FAILED: 'PROFILE_CREATE_FAILED',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  PROFILE_AVATAR_UPLOAD_FAILED: 'PROFILE_AVATAR_UPLOAD_FAILED',
  PROFILE_CLIENT_NOT_SUBSCRIBED: 'PROFILE_CLIENT_NOT_SUBSCRIBED',
  PROFILE_CLIENT_NOT_FOUND: 'PROFILE_CLIENT_NOT_FOUND',

  // ── Prisma generic ───────────────────────────────────────────────
  GENERIC_UNIQUE_CONSTRAINT: 'GENERIC_UNIQUE_CONSTRAINT',
  GENERIC_NOT_FOUND: 'GENERIC_NOT_FOUND',
  GENERIC_FOREIGN_KEY: 'GENERIC_FOREIGN_KEY',

  // ── Workout core (Phase 3 placeholder) ───────────────────────────
  WORKOUT_EXERCISE_NOT_FOUND: 'WORKOUT_EXERCISE_NOT_FOUND',
  WORKOUT_EXERCISE_DUPLICATE_NAME: 'WORKOUT_EXERCISE_DUPLICATE_NAME',
  WORKOUT_EXERCISE_FORBIDDEN: 'WORKOUT_EXERCISE_FORBIDDEN',
  WORKOUT_ROUTINE_NOT_FOUND: 'WORKOUT_ROUTINE_NOT_FOUND',
  WORKOUT_SESSION_NOT_FOUND: 'WORKOUT_SESSION_NOT_FOUND',
  WORKOUT_SESSION_FORBIDDEN: 'WORKOUT_SESSION_FORBIDDEN',
  WORKOUT_SESSION_ALREADY_ACTIVE: 'WORKOUT_SESSION_ALREADY_ACTIVE',
  WORKOUT_SESSION_NOT_ACTIVE: 'WORKOUT_SESSION_NOT_ACTIVE',
  WORKOUT_SESSION_ALREADY_COMPLETED: 'WORKOUT_SESSION_ALREADY_COMPLETED',
  WORKOUT_SET_NOT_FOUND: 'WORKOUT_SET_NOT_FOUND',
  WORKOUT_SET_ORDER_CONFLICT: 'WORKOUT_SET_ORDER_CONFLICT',
  WORKOUT_BATCH_SYNC_FAILED: 'WORKOUT_BATCH_SYNC_FAILED',
  WORKOUT_WEEKLY_STATS_UNAVAILABLE: 'WORKOUT_WEEKLY_STATS_UNAVAILABLE',

  // ── Program / Coach / Assignment (Phase 4 placeholder) ──────────
  PROGRAM_NOT_FOUND: 'PROGRAM_NOT_FOUND',
  PROGRAM_DUPLICATE_NAME: 'PROGRAM_DUPLICATE_NAME',
  PROGRAM_FORBIDDEN: 'PROGRAM_FORBIDDEN',
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_ALREADY_EXISTS: 'ASSIGNMENT_ALREADY_EXISTS',
  ASSIGNMENT_CLIENT_MISMATCH: 'ASSIGNMENT_CLIENT_MISMATCH',
  COACH_ALREADY_EXISTS: 'COACH_ALREADY_EXISTS',
  COACH_CLIENT_NOT_LINKED: 'COACH_CLIENT_NOT_LINKED',
  COACH_CLIENT_NOT_FOUND: 'COACH_CLIENT_NOT_FOUND',
  COACH_PROGRAM_LOCKED: 'COACH_PROGRAM_LOCKED',
  PROGRAM_ROUTINE_NOT_FOUND: 'PROGRAM_ROUTINE_NOT_FOUND',
  PROGRAM_ROUTINE_DAY_CONFLICT: 'PROGRAM_ROUTINE_DAY_CONFLICT',
  PROGRAM_REQUIRED: 'PROGRAM_REQUIRED',
  ROUTINE_TEMPLATE_NOT_FOUND: 'ROUTINE_TEMPLATE_NOT_FOUND',
  COACH_INVITE_NOT_FOUND: 'COACH_INVITE_NOT_FOUND',
  COACH_INVITE_INVALID: 'COACH_INVITE_INVALID',
  COACH_INVITE_EXPIRED: 'COACH_INVITE_EXPIRED',
  COACH_INVITE_MAX_ATTEMPTS: 'COACH_INVITE_MAX_ATTEMPTS',
  COACH_INVITE_ALREADY_REDEEMED: 'COACH_INVITE_ALREADY_REDEEMED',
  COACH_INVITE_REVOKED: 'COACH_INVITE_REVOKED',
  COACH_INVITE_EMAIL_MISMATCH: 'COACH_INVITE_EMAIL_MISMATCH',
  COACH_INVITE_EMAIL_ALREADY_COACH: 'COACH_INVITE_EMAIL_ALREADY_COACH',
  COACH_NOT_FOUND: 'COACH_NOT_FOUND',
  COACH_ALREADY_DEACTIVATED: 'COACH_ALREADY_DEACTIVATED',
  COACH_NOT_DEACTIVATED: 'COACH_NOT_DEACTIVATED',
  COACH_DEACTIVATED: 'COACH_DEACTIVATED',
  COACH_MAX_CLIENTS_BELOW_ACTIVE: 'COACH_MAX_CLIENTS_BELOW_ACTIVE',

  // ── Subscription / RevenueCat (Phase 5 placeholder) ─────────────
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_SYNC_FAILED: 'SUBSCRIPTION_SYNC_FAILED',
  SUBSCRIPTION_HISTORY_FETCH_FAILED: 'SUBSCRIPTION_HISTORY_FETCH_FAILED',
  REVENUECAT_INVALID_SIGNATURE: 'REVENUECAT_INVALID_SIGNATURE',
  REVENUECAT_UNKNOWN_EVENT: 'REVENUECAT_UNKNOWN_EVENT',
  REVENUECAT_USER_MISMATCH: 'REVENUECAT_USER_MISMATCH',
  REVENUECAT_DUPLICATE_EVENT: 'REVENUECAT_DUPLICATE_EVENT',

  // ── Workout ancillaries (Phase 6 placeholder) ───────────────────
  STANDALONE_NOT_FOUND: 'STANDALONE_NOT_FOUND',
  STANDALONE_ALREADY_COMPLETED: 'STANDALONE_ALREADY_COMPLETED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_PERMISSION_DENIED: 'SESSION_PERMISSION_DENIED',
  TODAY_NO_ASSIGNED_WORKOUT: 'TODAY_NO_ASSIGNED_WORKOUT',
  STATS_RANGE_INVALID: 'STATS_RANGE_INVALID',
  CLASS_NOT_FOUND: 'CLASS_NOT_FOUND',
  CLASS_CLIENT_ALREADY_REMOVED: 'CLASS_CLIENT_ALREADY_REMOVED',

  // ── Gamification (Phase 7 placeholder) ──────────────────────────
  COIN_INSUFFICIENT_BALANCE: 'COIN_INSUFFICIENT_BALANCE',
  COIN_HISTORY_FETCH_FAILED: 'COIN_HISTORY_FETCH_FAILED',
  SHOP_ITEM_NOT_FOUND: 'SHOP_ITEM_NOT_FOUND',
  SHOP_ITEM_ALREADY_OWNED: 'SHOP_ITEM_ALREADY_OWNED',
  SHOP_ITEM_OUT_OF_STOCK: 'SHOP_ITEM_OUT_OF_STOCK',
  COSMETIC_NOT_FOUND: 'COSMETIC_NOT_FOUND',
  COSMETIC_NOT_OWNED: 'COSMETIC_NOT_OWNED',
  COSMETIC_NOT_EQUIPPABLE: 'COSMETIC_NOT_EQUIPPABLE',
  MISSION_NOT_FOUND: 'MISSION_NOT_FOUND',
  MISSION_CLOSED: 'MISSION_CLOSED',
  MISSION_NOT_RAFFLE: 'MISSION_NOT_RAFFLE',
  MISSION_ALREADY_CLOSED: 'MISSION_ALREADY_CLOSED',
  MISSION_COUPON_NON_REPEATABLE: 'MISSION_COUPON_NON_REPEATABLE',
  MISSION_RAFFLE_REQUIRES_PARTNER: 'MISSION_RAFFLE_REQUIRES_PARTNER',
  MISSION_RAFFLE_REQUIRES_MAX_WINNERS: 'MISSION_RAFFLE_REQUIRES_MAX_WINNERS',
  RAFFLE_TOO_MANY_WINNERS: 'RAFFLE_TOO_MANY_WINNERS',
  PARTNER_NOT_FOUND: 'PARTNER_NOT_FOUND',
  PARTNER_HAS_MISSIONS: 'PARTNER_HAS_MISSIONS',
  LEADERBOARD_FETCH_FAILED: 'LEADERBOARD_FETCH_FAILED',
  LEADERBOARD_PERIOD_INVALID: 'LEADERBOARD_PERIOD_INVALID',
  POSE_IMAGE_INVALID: 'POSE_IMAGE_INVALID',
  POSE_ANALYSIS_FAILED: 'POSE_ANALYSIS_FAILED',
  POSE_FORM_NOT_FOUND: 'POSE_FORM_NOT_FOUND',

  // ── Form Library & Exercise Ratings ───────────────────────────────
  FORM_LIBRARY_NOT_FOUND: 'FORM_LIBRARY_NOT_FOUND',
  EXERCISE_RATING_NOT_FOUND: 'EXERCISE_RATING_NOT_FOUND',
  EXERCISE_RATING_ALREADY_EXISTS: 'EXERCISE_RATING_ALREADY_EXISTS',
} as const;

/** Union of all error code string literals */
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
